"""Sphinx extension that builds Word (.docx) documents."""
from importlib.metadata import PackageNotFoundError, version as _version

from sphinx.util.osutil import make_filename
from sphinx_docx.builder import DocxBuilder

try:
    __version__ = _version('sphinx-docx')
except PackageNotFoundError:  # running from a source tree, not installed
    __version__ = '0.0.0.dev0'

__all__ = ['DocxBuilder', 'setup', '__version__']


def setup(app):
    """Register the docx builder and its configuration values with Sphinx."""
    app.add_builder(DocxBuilder)

    def default_docx_documents(conf):
        """Build the default ``docx_documents`` entry: one file from the master doc."""
        start_doc = conf.master_doc
        filename = '%s.docx' % make_filename(conf.project)
        title = conf.project
        # author configuration value is available from Sphinx 1.8
        author = getattr(conf, 'author', 'sphinx_docx')
        properties = {
            'title': title,
            'creator': author,
            'subject': '',
            'category': '',
            'description': 'This document generated by sphinx_docx',
            'keywords': ['python', 'Office Open XML', 'Word'],
        }
        toc_only = False
        return [(start_doc, filename, properties, toc_only)]

    app.add_config_value('docx_documents', default_docx_documents, 'env')
    app.add_config_value('docx_style', '', 'env')
    app.add_config_value('docx_pagebreak_before_section', 0, 'env')
    app.add_config_value('docx_pagebreak_before_file', 0, 'env')
    app.add_config_value('docx_pagebreak_before_table_of_contents', -1, 'env')
    app.add_config_value('docx_pagebreak_after_table_of_contents', 0, 'env')
    app.add_config_value('docx_coverpage', 1, 'env')
    app.add_config_value('docx_update_fields', False, 'env')
    app.add_config_value('docx_bake_property_fields', True, 'env')
    app.add_config_value('docx_table_options', {
        'landscape_columns': 0,
        'in_single_page': False,
        'row_splittable': True,
        'header_in_all_page': False,
    }, 'env')
    app.add_config_value('docx_style_names', {}, 'env')
    app.add_config_value('docx_nested_character_style', True, 'env')

    return {
        'version': __version__,
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
